#!/bin/bash
touch Crawl_verbs.po
touch Crawl_korean.po
touch Crawl_words.po

xgettext --omit-header --keyword --keyword=V_ -M-verb -c --force-po --from-code utf-8 -o - *.cc | grep msgstr | sed 's/msgstr\(.*\)/msgid\1\nmsgstr ""\n/g' >> Crawl_verbs.po && msguniq Crawl_verbs.po -o Crawl_verbs.po

xgettext --keyword --keyword=M_ -c -j --force-po --from-code utf-8 -o Crawl_words.po *.cc *.h
xgettext --keyword=N_ --keyword=P_:1c,2 -c -j --from-code utf-8 -o Crawl_korean.po *.cc mutation.h
