#!/bin/bash
touch Crawl_verbs.po
touch Crawl_mutation.po
touch Crawl_korean.po
#xgettext --omit-header --keyword --keyword=V_ -M-verb -c -j --force-po --from-code utf-8 -o Crawl_verbs.po *.cc

xgettext --omit-header --keyword --keyword=V_ -M-verb -c --force-po --from-code utf-8 -o - *.cc | grep msgstr | sed 's/msgstr\(.*\)/msgid\1\nmsgstr ""\n/g' >> Crawl_verbs.po
msguniq Crawl_verbs.po -o Crawl_verbs.po

xgettext --omit-header --keyword=N_ -c -j --force-po --from-code utf-8 -o Crawl_mutation.po mutation-data.h
xgettext --keyword=N_ -c -j -x Crawl_mutation.po --from-code utf-8 -o Crawl_korean.po *.cc
